### ISSUE TITLE
Error running shopping-cart example

### ISSUE THREAD

**Issue by jrochenrfm** [rjrodger/seneca-examples#13]
Using seneca 0.5.20.

steps:

- `$ node app.js -p 3000`
- visit `http://localhost:3000`

Error is shown below:

```
ERROR	act	engage	-	OUT	i303sfktwfx6	role:engage,cmd:set	Seneca/0.5.20/aimvnzu7913a/1409924365092/-: load-without-query: [ 'load-without-query', { entity: $-/sys/engage:{id=;} } ]	action-execute	{id=i303sfktwfx6,gate=false,ungate=true,pattern=role:engage,cmd:set,plugin={name=engage,tag=undefined},time={start=1409924375013}}	Error: Seneca/0.5.20/aimvnzu7913a/1409924365092/-: load-without-query: [ 'load-without-query', { entity: $-/sys/engage:{id=;} } ]
    at Seneca.fail (~/projects/seneca/lib/seneca.js:1670:15)
    at Entity.load$ (~/projects/seneca/lib/entity.js:191:14)
    at ensure_engage (~/projects/seneca-examples/shopping-cart/node_modules/seneca-engage/engage.js:39:16)
    at Seneca.cmd_set (~/projects/seneca-examples/shopping-cart/node_modules/seneca-engage/engage.js:99:5)
    at Object.$.executor.execute.fn (~/projects/seneca/lib/seneca.js:1334:24)
    at Object._onImmediate (~/projects/seneca/lib/executor.js:93:14)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by rjrodger** [comment]
should now be fixed with seneca 0.6.1
