### ISSUE TITLE
user-accounts not working anymore on latest versions

### ISSUE THREAD

**Issue by nfantone** [rjrodger/seneca-examples#26]
After updating npm dependecies to:

```
    "express": "~4.13.4",
    "body-parser": "~1.15.0",
    "cookie-parser": "~1.4.1",
    "method-override": "~2.3.5",
    "express-session": "~1.13.0",
    "serve-static": "~1.10.2",
    "optimist": "~0.6.1",
    "ejs": "~2.4.1",
    "ejs-locals": "~1.0.2",
    "seneca": "plugin",
    "seneca-user": "~1.0.0",
    "seneca-auth": "~0.4.0",
    "seneca-admin": "~0.2.0",
    "seneca-jsonrest-api": "~0.3.1",
    "seneca-perm": "~0.5.6",
    "seneca-data-editor": "~0.2.0"
```

The example just doesn't work anymore. Specifically, `seneca-data-editor` and `seneca-admin` plugins fail with:

```
cmd:load,role:entity,ent:{},name:user,base:sys,zone:null}   ENTRY   (ozx7g) -   seneca: Action cmd:load,role:entity callback threw: useract.register is not a function. act_callback    {message:useract.register is not a function,pattern:cmd:load,role:entity,instance:Seneca/1.1.0/wyy1pxnq0z7i/145 TypeError: useract.register is not a function
```

**Comment by sminodonte** [comment]
same problem: 
"TypeError: u.register is not a function"

**Comment by nfantone** [comment]
![](https://i.ytimg.com/vi/hlQvNZnCoBI/hqdefault.jpg)

**Comment by heriipurnama** [comment]
yes iam same problem: 
"TypeError: u.register is not a function"
 node app.js 
2016-04-02T14:29:33.843Z mw3vhpn6q33c/1459607373822/22650/- INFO    hello   Seneca/2.0.0/mw3vhpn6q33c/1459607373822/22650/- 
express-session deprecated undefined resave option; provide resave option app.js:58:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:58:9
/home/heriipurnama/Documents/node/seneca-examples/user-accounts/app.js:89
u.register({nick:'u1',name:'nu1',email:'u1@example.com',password:'u1',active:true})
  ^

TypeError: u.register is not a function
    at Object.<anonymous> (/home/heriipurnama/Documents/node/seneca-examples/user-accounts/app.js:89:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by tfoutrein** [comment]
Same problem for me 

D:\Projets\R&D\MicoServices\seneca-examples-master\user-accounts>node app.js
2016-04-15T14:23:08.897Z gr3ca7w493nf/1460730188887/864/- INFO  hello   Seneca/2.0.1/gr3ca7w493nf/1460730188887/864/-
express-session deprecated undefined resave option; provide resave option app.js:58:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:58:9
D:\Projets\R&D\MicoServices\seneca-examples-master\user-accounts\app.js:89
u.register({nick:'u1',name:'nu1',email:'u1@example.com',password:'u1',active:true})
  ^

TypeError: u.register is not a function
    at Object.<anonymous> (D:\Projets\R&D\MicoServices\seneca-examples-master\user-accounts\app.js:89:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

D:\Projets\R&D\MicoServices\seneca-examples-master\user-accounts>

**Comment by heriipurnama** [comment]
Iam Now work. .  With Seneca 0.62,  just try with Seneca 0.62.. .

**Comment by KristinaMatuleviciute** [comment]
Thanks heriipurnama, 
working with dependencies updated and "seneca": "0.6.2",
"dependencies": {
    "express": "~4.13.4",
    "body-parser": "~1.15.1",
    "cookie-parser": "~1.4.2",
    "method-override": "~2.3.6",
    "express-session": "~1.13.0",
    "serve-static": "~1.10.2",
    "optimist": "~0.6.1",
    "ejs": "~2.4.1",
    "ejs-locals": "~1.0.2",
    "seneca": "0.6.2",
    "seneca-user": "~1.0.1",
    "seneca-auth": "~1.0.1",
    "seneca-admin": "~0.2.0",
    "seneca-jsonrest-api": "~0.3.1",
    "seneca-perm": "~0.5.6",
    "seneca-data-editor": "~0.2.0"
  }
