### ISSUE TITLE
Not working.. it gives the following error

### ISSUE THREAD

**Issue by nagkumar** [rjrodger/seneca-examples#40]
{"kind":"add","case":"ADD","id":"transport_client_12","pattern":"cmd:*,role:user","name":"transport_client","level":"debug","plugin_name":"client$","seneca":"f7a3um19u28h/1512021509872/167/3.4.3/-","when":1512021510185}
/wkr/seneca-examples-master/micro-services/node_modules/express/lib/application.js:177
    throw new TypeError('app.use() requires middleware functions');
    ^

TypeError: app.use() requires middleware functions
    at Function.use (/wkr/seneca-examples-master/micro-services/node_modules/express/lib/application.js:177:11)
    at Object.<anonymous> (/wkr/seneca-examples-master/micro-services/services/web-app.js:17:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

Seneca Fatal Error
==================

Message: seneca: Action init:user failed: seneca.make is not a function.

**Comment by samsfisherCsy** [comment]
Raise this error too，I find another answer by overflow. 
https://stackoverflow.com/questions/39480013/app-use-requires-middleware-functions-app-use-seneca-exportweb
